name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # master 브랜치에 push할 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: ./.github/actions/checkout

    - name: Setup Node.js
      uses: ./.github/actions/setup-node

    - name: Build the project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: ./.github/actions/deploy-gh-pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ # ./public  # 배포할 디렉토리
